import requests
import re
from pathlib import Path

LINK_DOCS = "https://tailwindcss.com/docs/customizing-colors"
LINK_DATA_HOSTED = "https://raw.githubusercontent.com/tailwindlabs/tailwindcss/master/src/public/colors.js"

rawRequest = requests.get(LINK_DATA_HOSTED)

paletteIndex = {}

for entry in re.findall("(\w*)\:\s{((.|\n)*?)}", rawRequest.text):
    paletteName = entry[0]
    paletteContents = entry[1]

    paletteIndex[paletteName] = {}

    for swatch in re.findall("([\w\d]+)[:\s]+'(.*)'", paletteContents):
        # https://stackoverflow.com/a/29643643.
        hexCode = swatch[1][1:]
        rgbCode = tuple(int(hexCode[i : i + 2], 16) for i in (0, 2, 4))

        paletteIndex[paletteName][swatch[0]] = rgbCode


# Very hacky JSON to lua converter.
# Rojo provides this, but I want to instantiate all of our colors upfront.
def tupleToColor3(tuple):
    return f"Color3.new({','.join(str(value/255) for value in tuple)})"

def paletteToLua(palette):
    return "{"+ ",".join(f'[{key}] = {tupleToColor3(value)}' for key, value in palette.items() ) + "}"

out = "return {" + ",".join(
    f'["{key}"] = {paletteToLua(value)}' for key, value in paletteIndex.items()
) + "}"

# TODO: I'd rather not check-in this build file. Some kind of build process might be nice? With Remodel?
# Open adjacent to script.
with Path(__file__).with_name('WxColors.lua').open("w") as file:
    file.writelines("\n".join([
        f"-- Autogenerated with \"{Path(__file__).name}\". Please don't edit manually! :)",
        f"-- Docs: {LINK_DOCS}.",
        out
	]))